MINERAL_TYPES = [
    "BORONIDE",
    "CORBOMITE",
    "CORUNDIUM",
    "DURANIUM",
    "GALLICITE",
    "MERCASSIUM",
    "NEUTRONIUM",
    "SORIUM",
    "TRITANIUM",
    "URIDIUM",
    "VENDARITE",
]
